version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopasswd
    volumes:
      - ./container-data/minio:/data
    command: server /data --console-address ":9090"


  postgresql:
    image: docker.io/library/postgres:16.4-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresqluser
      POSTGRES_PASSWORD: postgresqlpasswd
    volumes:
      - ./container-data/postgresql:/var/lib/postgresql/data
  
  adminer:
    image: docker.io/library/adminer
    restart: always
    depends_on: postgresql
    ports:
      - 9091:8080
