services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopasswd
    volumes:
      - ./container-data/minio:/data
    command: server /data --console-address ":9090"
    networks:
      - paperless-network

  postgres-db:
    image: docker.io/library/postgres:16.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DATABASE: postgres
    volumes:
      - ./container-data/postgresql:/var/lib/postgresql/data
    networks:
      - paperless-network
  
  adminer:
    image: docker.io/library/adminer
    depends_on: 
      - postgres-db
    ports:
      - "9091:8080"
    networks:
      - paperless-network

  rabbitmq:
    image: docker.io/library/rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "9093:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_passwd
    networks:
      - paperless-network

  rest-api:
    image: fhtw.at/swkom/paperless-api:latest
    depends_on:
      - postgres-db
      - minio
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      minioAccessKey: ${minioAccessKey}
      minioSecretKey: ${minioSecretKey}
      dbUrl: jdbc:postgresql://paperless-postgres-db-1:5432/postgres
      dbPasswd: postgresql
      dbUser: postgresql
      minioEndpoint: http://paperless-minio-1:9000
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_passwd
      RABBITMQ_DEFAULT_HOST: paperless-rabbitmq-1
    networks:
      - paperless-network

  frontend:
    image: caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend/build:/srv
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - rest-api
    networks:
      - paperless-network

  ocr-worker:
    build: ocr-worker
    image: fhtw.at/swkom/ocr-worker:latest
    depends_on:
      - rest-api
    networks:
        - paperless-network

networks:
  paperless-network:
    #driver: host
    driver: bridge
