services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopasswd
    volumes:
      - ./container-data/minio:/data
    command: server /data --console-address ":9090"
    networks:
      - paperless-network

  postgresql:
    image: docker.io/library/postgres:16.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresqluser
      POSTGRES_PASSWORD: postgresqlpasswd
    volumes:
      - ./container-data/postgresql:/var/lib/postgresql/data
    networks:
      - paperless-network
  
  adminer:
    image: docker.io/library/adminer
    depends_on: 
      - postgresql
    ports:
      - 9091:8080
    networks:
      - paperless-network

  rest-api:
    image: fhtw.at/swkom/paperless-api:latest
    depends_on:
      - postgresql
      - minio
    ports:
      - 8081:8081
    networks:
      - paperless-network

networks:
  paperless-network:
    driver: bridge
